repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        exclude: ^tests/
        additional_dependencies:
          - flask
          - flask-sqlalchemy
          - pydantic
          - sqlalchemy
        args: [--config-file=mypy.ini]
